stages:
  - build
  - release


# =============================================================================
# Perform the unit test
# =============================================================================

test_python_3_10:
  stage: build  # Docker-image creation and tests can run in parallel
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/redis
      alias: redis
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres
      alias: postgres
  tags:
    - ito
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/python:3.10
  variables:
    REDSQL_REDIS_HOST: "redis"
    REDSQL_REDIS_PORT: "6379"
    REDSQL_REDIS_DB: 0
    POSTGRES_DB: "redsql_testing"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    REDSQL_DB_URL: "postgresql://postgres:$POSTGRES_PASSWORD@postgres:5432/redsql_testing"

  script:
    - pip install -r requirements.txt
    - pip install pytest==8.3.2 pandas==2.2.2 # Dedicated testing requirements
    - PYTHONPATH="${PYTHONPATH}:.:test" pytest --junitxml=report.xml --log-cli-level=DEBUG test
  artifacts:  # Collect test results
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml


# =============================================================================
# Build and release image
# =============================================================================

# Build image template
.build-image-template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  variables:
    DOCKERFILE_PATH: $CI_PROJECT_DIR/docker/Dockerfile
    # Internal registry
    INTERNAL_REGISTRY_DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    INTERNAL_REGISTRY_DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    # External registry
    EXTERNAL_REGISTRY_DOCKER_IMAGE: $EXT_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    EXTERNAL_REGISTRY_DOCKER_IMAGE_LATEST: $EXT_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
  tags:
    - ito


# Build and release an image to the internal gitlab registry
build-image:
  extends: .build-image-template
  stage: build
  script:
    - |
      cat <<EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          },
          "$EXT_REGISTRY": {
            "username": "$EXT_REGISTRY_USER",
            "password": "$EXT_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $DOCKERFILE_PATH
      --build-arg TOKEN_PYRDP_COMMONS=$TOKEN_PYRDP_COMMONS
      --destination $INTERNAL_REGISTRY_DOCKER_IMAGE
      --destination $INTERNAL_REGISTRY_DOCKER_IMAGE_LATEST
#      --no-push
#      --no-push-cache
  except:
    - development
    - main
    - master
    - 44-kaniko-not-pushing-to-ext-registry
      
# Build and release an image to the internal and external gitlab registries
build-and-release-image:
  extends: .build-image-template
  stage: release
  script:
    - |
      cat <<EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          },
          "$EXT_REGISTRY": {
            "username": "$EXT_REGISTRY_USER",
            "password": "$EXT_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $DOCKERFILE_PATH
      --build-arg TOKEN_PYRDP_COMMONS=$TOKEN_PYRDP_COMMONS
      --destination $INTERNAL_REGISTRY_DOCKER_IMAGE
      --destination $INTERNAL_REGISTRY_DOCKER_IMAGE_LATEST
      --destination $EXTERNAL_REGISTRY_DOCKER_IMAGE
      --destination $EXTERNAL_REGISTRY_DOCKER_IMAGE_LATEST
  only:
    - development
    - main
    - master
    - 44-kaniko-not-pushing-to-ext-registry
