[project]
name = "redsql"
version = "0.1.0.post1.dev0"
description = "Generic Redis to SQL data synchronizer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prometheus-client>=0.24.1",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "pyrdp-commons @ git+https://github.com/AIT-RDP/pyrdp-commons.git@development",
    "python-dateutil>=2.9.0.post0",
    "redis>=7.2.0",
    "sqlalchemy>=2.0.46",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
