{
 "title": "RedSQL Details",
 "description": "Detailed metrics on the RedSQL operation monitored by Prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(redsql_channel_alive, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(redsql_channel_alive{job=$job}, instance)"
    }
   },
   {
    "name": "channel_name",
    "label": "Channel Name",
    "query": {
     "query": "label_values(redsql_channel_alive{job=\"$job\", instance=\"$instance\"}, channel_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Base Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])*100.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Open FD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(last_over_time(process_open_fds{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) / last_over_time(process_max_fds{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))*100.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Chn. Restarts",
   "type": "stat",
   "description": "Total amount of channel restarts on all channels",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(redsql_channel_restarts_total{job=\"$job\", instance=\"$instance\"}[$__interval]) - min_over_time(redsql_channel_restarts_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(redsql_channel_alive{job=\"$job\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{channel_name}}"
    }
   ]
  },
  {
   "title": "Avg. In Msg. Rate",
   "type": "stat",
   "description": "The average input message rate on the selected period",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redsql_processed_messages_total{job=\"$job\", instance=\"$instance\", type=\"in\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Error Rate",
   "type": "stat",
   "description": "The average message error rate on all messages",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redsql_processed_messages_total{job=\"$job\", instance=\"$instance\", type=\"err_general\"}[$__rate_interval])) + sum(rate(redsql_processed_messages_total{job=\"$job\", instance=\"$instance\", type=\"err_format\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Out Row Rate",
   "type": "stat",
   "description": "The average output rate on the selected period in table rows",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redsql_inserted_table_rows_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. SQL Query Rate",
   "type": "stat",
   "description": "The average SQL query rate without cache lookups",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(redsql_sql_queries_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global Operation Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Process Load"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Process memory"
    }
   ]
  },
  {
   "title": "Total Messag Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(redsql_processed_messages_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Message: {{type}}"
    }
   ]
  },
  {
   "title": "Total SQL Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(redsql_inserted_table_rows_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Inserted Rows"
    },
    {
     "expr": "sum(rate(redsql_sql_queries_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Executed SQL Queries"
    }
   ]
  },
  {
   "title": "Operation Details: Channel \"$channel_name\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "channel_name"
  },
  {
   "title": "Messag Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(redsql_processed_messages_total{job=\"$job\", instance=\"$instance\", channel_name=~\"$channel_name\"}[$__rate_interval])",
     "legendFormat": "Message: {{type}}"
    }
   ]
  },
  {
   "title": "SQL Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(redsql_inserted_table_rows_total{job=\"$job\", instance=\"$instance\", channel_name=~\"$channel_name\"}[$__rate_interval])",
     "legendFormat": "Inserted Rows"
    },
    {
     "expr": "sum(rate(redsql_sql_queries_total{job=\"$job\", instance=\"$instance\", channel_name=~\"$channel_name\"}[$__rate_interval]))",
     "legendFormat": "Executed SQL Queries"
    }
   ]
  }
 ]
}