"""
Implements the main command line interface of RedSQL
"""

import argparse
import logging
import os

import yaml

logger = logging.getLogger(__name__)


def main(argv=None, prog=None):
    """
    Parses the commandline arguments, reads the configuration and starts the main program flow

    :param argv:
    :param prog:
    """

    logging.basicConfig(format="%(asctime)s %(name)s %(levelname)s: %(message)s", level=logging.DEBUG)

    parser = argparse.ArgumentParser(prog=prog, description="Feeds data from Redis to some SQL database")
    parser.add_argument("--config_file", metavar="CONF", default="redsql.yaml",
                        help="The main YAML configuration describing the translation process")
    args = parser.parse_args(args=argv)

    logger.debug("Parse main YAML configuration file '%s'", args.config_file)
    config = load_config(args.config_file)

    pass  # TODO: Implement the main program flow


def load_config(config_file: str) -> dict:
    """
    Parses the YAML configuration, preprocesses it and returns the resulting structure of dictionaries
    :param config_file: The path of the main configuration file
    :return: The obtained configuration as a structure of nested dicts as generated by the YAML loader
    """

    config_file = os.path.abspath(config_file)
    if not os.path.isfile(config_file):
        raise FileNotFoundError(f"The main configuration file '{config_file}' is not found")

    with open(config_file, "r") as f:
        config = yaml.load(f, Loader=yaml.Loader)

    if not config.get("version", 1) == 1:
        raise SyntaxError("Invalid configuration version. Only version 1 is supported.")

    return config
